scrape_configs:
  - job_name: 'prometheus-scrape-test'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
rule_files:
  - "rules.yml"
alerting:
   alertmanagers:
     - static_configs: 
         - targets:
             - alertmanager:9093